### ISSUE TITLE
windows compile

### ISSUE THREAD

**Issue by guyulmaz** [b3ntly/vue-grpc#2]
Hello,

I wanted to share some of my observations/experiences  with this project at windows 10 machine enviroment.

linux and bash is needed to compile the project.
So I had to change some files to make it work at windows.
I also updated the dependencies in package.json to latest existing versions.
get_go_deps.bat and protogen.bat added
Also 
go get github.com\improbable-eng\grpc-web\ 
was missing at get_go_deps.bat/sh, so I added this.

There was a little error with latest versions.
change import {grpc, BrowserHeaders, Metadata, **Code**} from "grpc-web-client";
change grpc.Code to Code

I had to change package.json to make it find protogen.bat for windows enviroment

debugging the server with vsCode was problamatic, step over/into not working at breakpoints.
So I installed https://www.jetbrains.com/go/
debug is perfect with it.

I'm thinking to improve the project with:
1- try to use oauth2 with grpc at server and vuejs client
2- try to use vuetify, quasar, onsen vuejs web frameworks at client side. How can typescript effect their usage.
3- try to use firebase auth, db, storage, hosting
4- try to deploy the go server to digital ocean dokku enviroment.
5- use sqlite and mariaDB as db

**Comment by beeekind** [comment]
This project is no longer actively maintained, feel free to fork it - I've added the MIT license and suggest any forks do the same although you don't have to.

If you do extend the project in a meaningful way please let me know so I can link to it in my README for future users to access.
